### ISSUE TITLE
Permissions for viewing/creating backups

### ISSUE THREAD

**Issue by EdwinHoksberg** [spatie/nova-backup-tool#13]
Hi! Is there currently a way to have permissions for a certain action? For example, I would like to add a user which can see and create backups, but can't delete them.
I don't know if this is a library limitation or a limitation of Nova itself.
Thanks!

**Comment by freekmurze** [comment]
It's perfectly doable of introducing permissions in this tool, there is no limitation of Nova itself here.

However, because I don't have a need for that myself, I'm probably won't invest time in this. 

I'm open for a fully tested, non-breaking, documented PR that adds this to the package.

**Comment by dillingham** [comment]
Because this tool doesn’t have a traditional usage of nova resource for the backup, the immediate gains of registering a policy for automatic and granular authorization are lost. 

You can still add a gate for viewing though. 

https://nova.laravel.com/docs/1.0/customization/tools.html#authorization

**Comment by muswanto** [comment]
I use this in NovaServiceProvider.php to authorize 3rd party package:

![image](https://user-images.githubusercontent.com/816709/48904478-141e5180-ee91-11e8-81f6-22379f76eee5.png)
