### ISSUE TITLE
Call to undefined method Spatie\Backup\BackupDestination\Backup::size()

### ISSUE THREAD

**Issue by goaround** [spatie/nova-backup-tool#95]
Hi,

my Backups Page is not loading because `Call to undefined method Spatie\Backup\BackupDestination\Backup::size()` here: https://github.com/spatie/nova-backup-tool/blob/860fd856a7f003134124b1fae0c6a52b068ba796/src/Http/Controllers/BackupsController.php#L31

I think it should call `sizeInBytes()` and not `size()`? There is no `size()` function: https://github.com/spatie/laravel-backup/blob/master/src/BackupDestination/Backup.php

**Comment by JackWH** [comment]
@freekmurze Hi! Just a friendly reminder about this issue... A faulty PR was merged in 4.1.2, and there's a discussion about rolling it back here: https://github.com/spatie/nova-backup-tool/pull/94

As the discussion was on a merged PR I think it might've slipped past you, as there's been another (broken) release made since. Thank you!

**Comment by quintenbuis** [comment]
Will be fixed by PR #104
